apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-zen-operator-cluster-role
  labels:
     app.kubernetes.io/instance: ibm-zen-operator-cluster-role
     app.kubernetes.io/managed-by: ibm-zen-operator
     app.kubernetes.io/name: ibm-zen-operator-cluster-role
rules:
- apiGroups:
  - ""
  - batch
  - extensions
  - apps
  - policy
  - rbac.authorization.k8s.io
  - autoscaling
  - route.openshift.io
  - authorization.openshift.io
  - networking.k8s.io
  - metrics.k8s.io
  - template.openshift.io
  resources:
  - pods
  - pods/log
  - poddisruptionbudgets
  - secrets
  - jobs
  - configmaps
  - deployments
  - deployments/scale
  - persistentvolumes
  - statefulsets
  - statefulsets/scale
  - replicasets
  - services
  - persistentvolumeclaims
  - cronjobs
  - pods/exec
  - pods/portforward
  - serviceaccounts
  - namespaces
  - roles
  - rolebindings
  - horizontalpodautoscalers
  - routes
  - routes/custom-host
  - ingresses
  - endpoints
  - cronjob
  - networkpolicies
  - events
  - jobs/status
  - pods/status
  - resourcequotas
  - resourcequotas/status
  - processedtemplates
  verbs:
  - apply
  - create
  - get
  - delete
  - watch
  - update
  - edit
  - exec
  - list
  - patch
  - scale
  - deletecollection
- apiGroups:
  - security.openshift.io 
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
  - use
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resourceNames:
  - ibm-zen-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - zen.cpd.ibm.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  - imagestreams/layers
  - imagestreams/secrets
  - imagestreams/status
  - imagestreamimages
  - imagestreamimports
  - imagestreammappings
  - imagestreamtags
  verbs:
  - create
  - delete
  - list
  - watch
  - get
  - patch
  - update
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  - buildconfigs/instantiate
  - buildconfigs/instantiatebinary
  - buildconfigs/webhooks
  - buildlogs
  - builds
  - builds/clone
  - builds/log
  - builds/details
  verbs:
  - create
  - delete
  - list
  - get
  - watch
  - update
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrole
  - clusterroles
  - clusterrolebinding
  - clusterrolebindings
  verbs:
  - create
  - delete
  - list
  - get
  - watch
  - update
  - patch
- apiGroups:
  - oidc.security.ibm.com
  resources:
  - client
  - clients
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
  - use
- apiGroups:
  - operator.ibm.com
  resources:
  - operandrequest
  - operandrequests
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
  - use