apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-zen-operator
  labels:
    app.kubernetes.io/instance: ibm-zen-operator
    app.kubernetes.io/managed-by: ibm-zen-operator
    app.kubernetes.io/name: ibm-zen-operator
    intent: projected
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-zen-operator
  template:
    metadata:
      labels:
        name: ibm-zen-operator
        intent: projected
        app.kubernetes.io/instance: ibm-zen-operator
        app.kubernetes.io/managed-by: ibm-zen-operator
        app.kubernetes.io/name: ibm-zen-operator
      annotations:
        productVersion: "4.0.0"
        productID: 068a62892a1e4db39641342e592daa25
        productMetric: FREE
        productName: IBM Cloud Platform Common Services
        productMetric: VIRTUAL_PROCESSOR_CORE
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 3
              preference:
                matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      serviceAccountName: ibm-zen-operator-serviceaccount
      initContainers:
        - command:
            - /bin/bash
            - '-c'
            - /setup/create-resources.sh
          env:
            - name: ZEN_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: icr.io/cpopen/ibm-zen-operator:6.0.0
          imagePullPolicy: Always
          name: setup-resources
          securityContext:
            privileged: false
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1024Mi
      containers:
        - name: ibm-zen-operator
          image: icr.io/cpopen/ibm-zen-operator:6.0.0
          imagePullPolicy: Always
          securityContext:
            privileged: false
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          args:
            - "--enable-leader-election"
            - "--leader-election-id=ibm-zen-operator"
            - "--max-concurrent-reconciles"
            - "8"
          env:
            - name: ZEN_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WATCH_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: namespace-scope
                  key: namespaces
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-zen-operator"
            - name: "REGISTRY_SECRET"
              value: "ibm-entitlement-key"
            - name: "ENTITLED_REGISTRY_NAME"
              value: "hyc-cloud-private-integration-docker-local.artifactory.swg-devops.com"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1024Mi
