apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rkvhunk/program.git
    targetRevision: HEAD
    path: dummy
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
