apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    app.kubernetes.io/instance: ibm-zen-operator-subscription
    app.kubernetes.io/managed-by: ibm-zen-operator
    app.kubernetes.io/name: ibm-zen-operator-subscription
  generation: 1
  name: ibm-zen-operator-subscription
spec:
  channel: v3
  installPlanApproval: Automatic
  name: ibm-zen-operator
  source: ibm-zen-operator-catalog
  sourceNamespace: openshift-marketplace
