---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cpd-viewer-role
rules:
- apiGroups:
  - ""
  - batch
  - extensions
  - apps
  - policy
  resources:
  - pods
  - pods/log
  - secrets
  - jobs
  - configmaps
  - deployments
  - endpoints
  - statefulsets
  - replicasets
  - services
  - persistentvolumeclaims
  - cronjobs
  - pods/exec
  - serviceaccounts
  - namespaces
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cpd-admin-role
rules:
- apiGroups:
  - ""
  - batch
  - extensions
  - apps
  - policy
  - rbac.authorization.k8s.io
  - autoscaling
  - route.openshift.io
  - authorization.openshift.io
  - networking.k8s.io
  - metrics.k8s.io
  resources:
  - pods
  - pods/log
  - poddisruptionbudgets
  - secrets
  - jobs
  - configmaps
  - deployments
  - deployments/scale
  - statefulsets
  - statefulsets/scale
  - replicasets
  - services
  - persistentvolumeclaims
  - cronjobs
  - pods/exec
  - pods/portforward
  - serviceaccounts
  - namespaces
  - roles
  - rolebindings
  - horizontalpodautoscalers
  - routes
  - routes/custom-host
  - ingresses
  - endpoints
  - cronjob
  - networkpolicies
  - events
  - jobs/status
  - pods/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - apply
  - create
  - get
  - delete
  - watch
  - update
  - edit
  - exec
  - list
  - patch
  - scale
  - deletecollection
- apiGroups:
  - cpd.ibm.com
  resources:
  - cpdinstalls
  - cpdinstalls/spec
  - cpdinstalls/status
  verbs:
  - apply
  - create
  - delete
  - edit
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  - buildconfigs/instantiate
  - buildconfigs/instantiatebinary
  - buildconfigs/webhooks
  - buildlogs
  - builds
  - builds/clone
  - builds/details
  - builds/log
  verbs:
  - create
  - delete
  - list
  - watch
  - get
  - patch
  - update
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  - imagestreams/layers
  - imagestreams/secrets
  - imagestreams/status
  - imagestreamimages
  - imagestreamimports
  - imagestreammappings
  - imagestreamtags
  verbs:
  - create
  - delete
  - list
  - watch
  - get
  - patch
  - update

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpd-norbac-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpd-editor-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpd-admin-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpd-viewer-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
imagePullSecrets:
- name: docker-pull-hyc-idp-docker-local-artifactory-swg-devops-com-base-registry
- name: docker-pull-hyc-idp-docker-local-artifactory-swg-devops-com-anotherbase-registry
- name: docker-pull-hyc-idp-docker-local-artifactory-swg-devops-com-base-registry-registry
---
apiVersion: security.openshift.io/v1
metadata:
  annotations: {}
  name: cpd-user-scc
kind: SecurityContextConstraints
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 1000320900
  uidRangeMax: 1000361000
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
---
apiVersion: security.openshift.io/v1
metadata:
  annotations: {}
  name: cpd-zensys-scc
kind: SecurityContextConstraints
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
runAsUser:
  type: MustRunAs
  uid: 1000321000
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
---
apiVersion: security.openshift.io/v1
metadata:
  annotations: {}
  name: cpd-noperm-scc
kind: SecurityContextConstraints
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups: []
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cpd-admin-rb
roleRef:
  kind: Role
  name: cpd-admin-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cpd-admin-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cpd-viewer-rb
roleRef:
  kind: Role
  name: cpd-viewer-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cpd-viewer-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cpd-editor-rb
roleRef:
  kind: Role
  name: cpd-admin-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: cpd-editor-sa
---
