apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-zen-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: icr.io/cpopen/ibm-zen-operator-catalog@sha256:b64f7dbb64e8fbfe01f335003f5636811356e9b64902c25a948d8efc82464a9d
  imagePullPolicy: Always
  displayName: Cloud Pak for Data
  publisher: IBM
